/**
 * Do not edit directly
 * Generated on Wed, 22 Mar 2023 13:11:57 GMT
 */

export const DarkColorsNeutral10 : string;
export const DarkColorsNeutral20 : string;
export const DarkColorsNeutral30 : string;
export const DarkColorsNeutral40 : string;
export const DarkColorsNeutral50 : string;
export const DarkColorsNeutral60 : string;
export const DarkColorsNeutral70 : string;
export const DarkColorsNeutral80 : string;
export const DarkColorsNeutral90 : string;
export const DarkColorsNeutral100 : string;
export const DarkColorsBackground0 : string;
export const DarkColorsPrimary0 : string;
export const DarkColorsPrimary10 : string;
export const DarkColorsPrimary20 : string;
export const DarkColorsPrimary30 : string;
export const DarkColorsPrimary40 : string;
export const DarkColorsPrimary50 : string;
export const DarkColorsPrimary60 : string;
export const DarkColorsPrimary70 : string;
export const DarkColorsPrimary80 : string;
export const DarkColorsPrimary90 : string;
export const DarkColorsPrimary100 : string;
export const DarkColorsSecondary0 : string;
export const DarkColorsSecondary10 : string;
export const DarkColorsSecondary20 : string;
export const DarkColorsSecondary30 : string;
export const DarkColorsSecondary40 : string;
export const DarkColorsSecondary50 : string;
export const DarkColorsSecondary60 : string;
export const DarkColorsSecondary70 : string;
export const DarkColorsSecondary80 : string;
export const DarkColorsSecondary90 : string;
export const DarkColorsSecondary100 : string;
export const DarkColorsRating100 : string;
export const DarkColorsError10 : string;
export const DarkColorsError100 : string;
export const DarkColorsSuccess10 : string;
export const DarkColorsSuccess100 : string;
export const DarkColorsGreen10 : string;
export const DarkColorsGreen100 : string;
export const LightColorsNeutral10 : string;
export const LightColorsNeutral20 : string;
export const LightColorsNeutral30 : string;
export const LightColorsNeutral40 : string;
export const LightColorsNeutral50 : string;
export const LightColorsNeutral60 : string;
export const LightColorsNeutral70 : string;
export const LightColorsNeutral80 : string;
export const LightColorsNeutral90 : string;
export const LightColorsNeutral100 : string;
export const LightColorsBackground0 : string;
export const LightColorsPrimary0 : string;
export const LightColorsPrimary10 : string;
export const LightColorsPrimary20 : string;
export const LightColorsPrimary30 : string;
export const LightColorsPrimary40 : string;
export const LightColorsPrimary50 : string;
export const LightColorsPrimary60 : string;
export const LightColorsPrimary70 : string;
export const LightColorsPrimary80 : string;
export const LightColorsPrimary90 : string;
export const LightColorsPrimary100 : string;
export const LightColorsSecondary0 : string;
export const LightColorsSecondary10 : string;
export const LightColorsSecondary20 : string;
export const LightColorsSecondary30 : string;
export const LightColorsSecondary40 : string;
export const LightColorsSecondary50 : string;
export const LightColorsSecondary60 : string;
export const LightColorsSecondary70 : string;
export const LightColorsSecondary80 : string;
export const LightColorsSecondary90 : string;
export const LightColorsSecondary100 : string;
export const LightColorsRating100 : string;
export const LightColorsError10 : string;
export const LightColorsError100 : string;
export const LightColorsSuccess10 : string;
export const LightColorsSuccess100 : string;
export const LightColorsGreen10 : string;
export const LightColorsGreen100 : string;
export const FontFamiliesPoppins : string;
export const LineHeights0 : string;
export const LineHeights1 : string;
export const LineHeights2 : string;
export const FontWeightsPoppins0 : string;
export const FontWeightsPoppins1 : string;
export const FontSize0 : string;
export const FontSize1 : string;
export const FontSize2 : string;
export const FontSize3 : string;
export const FontSize4 : string;
export const FontSize5 : string;
export const FontSize6 : string;
export const FontSize7 : string;
export const FontSize8 : string;
export const FontSize9 : string;
export const LetterSpacing0 : string;
export const ParagraphSpacing0 : string;
export const PoppinsHeadingRegular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsHeadingBold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH1Bold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH1Regular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH2Bold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH2Regular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH3Bold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH3Regular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH4Bold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH4Regular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH5Bold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsH5Regular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsParagraphBold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsParagraphRegular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsLabelBold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsLabelRegular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsSmallBold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsSmallRegular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsTinyBold : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const PoppinsTinyRegular : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: string, letterSpacing: string, paragraphSpacing: string, paragraphIndent: string, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextDecorationNone : string;
export const ParagraphIndent0 : string;
export const SizeXs : string;
export const SizeS : string;
export const SizeM : string;
export const SizeL : string;
export const SizeXl : string;
export const SizeXxl : string;
export const Neutral10 : string;
export const Neutral20 : string;
export const Neutral30 : string;
export const Neutral40 : string;
export const Neutral50 : string;
export const Neutral60 : string;
export const Neutral70 : string;
export const Neutral80 : string;
export const Neutral90 : string;
export const Neutral100 : string;
export const Background0 : string;
export const Primary0 : string;
export const Primary10 : string;
export const Primary20 : string;
export const Primary30 : string;
export const Primary40 : string;
export const Primary50 : string;
export const Primary60 : string;
export const Primary70 : string;
export const Primary80 : string;
export const Primary90 : string;
export const Primary100 : string;
export const Secondary0 : string;
export const Secondary10 : string;
export const Secondary20 : string;
export const Secondary30 : string;
export const Secondary40 : string;
export const Secondary50 : string;
export const Secondary60 : string;
export const Secondary70 : string;
export const Secondary80 : string;
export const Secondary90 : string;
export const Secondary100 : string;
export const Rating100 : string;
export const Error10 : string;
export const Error100 : string;
export const Success10 : string;
export const Success100 : string;
export const Green10 : string;
export const Green100 : string;